services:
  bot:
    image: ghcr.io/lunarcatowo/nyabot:latest
    container_name: nyabot
    restart: unless-stopped
    environment:
      - DB_URL=${DB_URL}
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - ROOT_USR=${ROOT_USR}
      - SENTRY_DSN=${SENTRY_DSN}
      - HOME=${HOME}
      - ENV=production
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=nyabot"
  watchtower:
    image: containrrr/watchtower
    container_name: nyabot-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --rolling-restart --scope nyabot --label-enable
    restart: always
    environment:
      - WATCHTOWER_POLL_INTERVAL=60