services:
  bot:
    image: ghcr.io/lunarcatowo/nyabot:latest
    container_name: nyabot
    restart: unless-stopped
    environment:
      - DB_URL=${DB_URL}
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - ROOT_USR=${ROOT_USR}
      - SENTRY_DSN=${SENTRY_DSN}
      - HOME_GUILD=${HOME_GUILD}
      - ENV=production
    networks:
      - dokploy-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=nya"

networks:
  dokploy-network:
    external: true