services:
  watchtower:
    image: containrrr/watchtower
    container_name: nya-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --rolling-restart --scope nya --label-enable
    restart: always
    environment:
      - WATCHTOWER_POLL_INTERVAL=60